# Generated by Django 5.2.7 on 2025-11-04 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade_label', models.CharField(max_length=10)),
                ('grade_index', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_climbs', to='core.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attempts', models.IntegerField()),
                ('sent', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='logs', to='core.climb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.appuser')),
            ],
        ),
        migrations.AddIndex(
            model_name='climb',
            index=models.Index(fields=['grade_index'], name='core_climb_grade_i_770da2_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', 'date'], name='core_log_user_id_62c1a0_idx'),
        ),
    ]
