# Generated by Django 5.2.7 on 2025-12-12 20:28

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='log',
            name='core_log_user_id_62c1a0_idx',
        ),
        migrations.RenameIndex(
            model_name='climb',
            new_name='idx_climb_grade',
            old_name='core_climb_grade_i_770da2_idx',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='display_name',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name contains invalid characters', regex='^[\\w\\s\\-\\\'\\".,()]+$'), core.validators.validate_no_sql_keywords]),
        ),
        migrations.AlterField(
            model_name='climb',
            name='grade_index',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(17)]),
        ),
        migrations.AlterField(
            model_name='climb',
            name='grade_label',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_grade', message='Grade label must be in format V0-V99', regex='^V\\d{1,2}$')]),
        ),
        migrations.AlterField(
            model_name='climb',
            name='location',
            field=models.CharField(blank=True, max_length=120, validators=[core.validators.validate_no_sql_keywords]),
        ),
        migrations.AlterField(
            model_name='climb',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name contains invalid characters', regex='^[\\w\\s\\-\\\'\\".,()]+$'), core.validators.validate_no_sql_keywords]),
        ),
        migrations.AlterField(
            model_name='log',
            name='attempts',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['display_name'], name='idx_user_display_name'),
        ),
        migrations.AddIndex(
            model_name='climb',
            index=models.Index(fields=['owner', '-created_at'], name='idx_climb_owner_date'),
        ),
        migrations.AddIndex(
            model_name='climb',
            index=models.Index(fields=['grade_index', 'name'], name='idx_climb_grade_name'),
        ),
        migrations.AddIndex(
            model_name='climb',
            index=models.Index(fields=['-created_at'], name='idx_climb_created'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', '-date'], name='idx_log_user_date'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['climb', '-date'], name='idx_log_climb_date'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['user', 'sent'], name='idx_log_user_sent'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['climb', 'sent', 'user'], name='idx_log_climb_sent_user'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['-date'], name='idx_log_date'),
        ),
        migrations.AddConstraint(
            model_name='climb',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_owner_name'),
        ),
    ]
